spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products
    username: root
    password: '#Mugshot23'
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  application:
    name: PRODUCT-SERVICE
server:
  port: 8083
